export const bankEntitiesPY = [
  { value: '1', label: 'Ueno Bank' },
  { value: '2', label: 'Banco Nacional de Fomento (BNF)' },
  { value: '3', label: 'Banco Central del Paraguay' },
  { value: '4', label: 'Banco Regional' },
  { value: '5', label: 'Banco Itaú Paraguay' },
  { value: '6', label: 'Banco Continental' },
  { value: '7', label: 'Banco BBVA Paraguay' },
  { value: '8', label: 'Banco GNB Paraguay' },
  { value: '9', label: 'Banco Atlas' },
  { value: '10', label: 'Banco Vision' },
  { value: '11', label: 'Banco Familiar' },
  { value: '12', label: 'Banco Sudameris' },
  { value: '13', label: 'Banco Amambay' },
  { value: '14', label: 'Banco BASA' },
  { value: '15', label: 'Banco Rio' },
  { value: '16', label: 'Banco Interfisa' },
]
